import contextlib
import io
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "tools"))

import fill_reference_addons  # noqa: E402

REAL_BYTEARRAY = (
    r"@ByteArray(Anthology 2.1 Standart "
    r"\xd0\xa1\xd1\x82\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb0\xd1\x80\xd1\x82)"
)
STANDART = "Anthology 2.1 Standart Стандарт"
HARD = "Anthology 2.1 HARD Сложный"
BASE_MOD = (
    "[WPN][0][WPN][R.A.K Weapon Pack Adaptation Global "
    "A.N.T.H.O.L.O.G.Y BASE (ЗБТ)]"
)
DISABLED_MOD = "Anthology Cutscenes v110 - CoP Cinematic Sync"
SEPARATOR = "[NPC] AI (не NPC)_separator"
SIMPLE_MOD = "simple_enabled"


def run_fill(mo2: Path, reference: Path, *extra: str) -> tuple[int, str]:
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer), contextlib.redirect_stderr(buffer):
        code = fill_reference_addons.main(
            [str(mo2), "--reference", str(reference), *extra]
        )
    return code, buffer.getvalue()


class QtByteArrayTests(unittest.TestCase):
    def test_real_mo2_selected_profile(self):
        self.assertEqual(
            fill_reference_addons.decode_qt_ini_value(REAL_BYTEARRAY),
            STANDART,
        )

    def test_plain_bytearray_ascii(self):
        self.assertEqual(
            fill_reference_addons.decode_qt_ini_value("@ByteArray(Default)"),
            "Default",
        )

    def test_plain_string(self):
        self.assertEqual(
            fill_reference_addons.decode_qt_ini_value(HARD),
            HARD,
        )


class ModlistTests(unittest.TestCase):
    def test_enabled_disabled_and_separators(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "modlist.txt"
            path.write_text(
                "\n".join(
                    [
                        "# This file was automatically generated by Mod Organizer.",
                        f"+{SIMPLE_MOD}",
                        f"-{DISABLED_MOD}",
                        f"+{SEPARATOR}",
                        f"+{BASE_MOD}",
                        "",
                    ]
                ),
                encoding="utf-8",
            )
            self.assertEqual(
                fill_reference_addons.parse_modlist(path),
                [SIMPLE_MOD, BASE_MOD],
            )


class FillAddonsTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.mo2 = self.root / "mo2"
        self.mods = self.mo2 / "mods"
        self.profiles = self.mo2 / "profiles"
        self.reference = self.root / "reference"
        self.mods.mkdir(parents=True)
        self.profiles.mkdir()
        (self.mo2 / "ModOrganizer.ini").write_text(
            "[General]\n"
            f"selected_profile={REAL_BYTEARRAY}\n",
            encoding="utf-8",
        )
        standart = self.profiles / STANDART
        hard = self.profiles / HARD
        standart.mkdir()
        hard.mkdir()
        (standart / "modlist.txt").write_text(
            "\n".join(
                [
                    "# This file was automatically generated by Mod Organizer.",
                    f"+{SIMPLE_MOD}",
                    f"-{DISABLED_MOD}",
                    f"+{SEPARATOR}",
                    f"+{BASE_MOD}",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        (hard / "modlist.txt").write_text(
            f"+{SIMPLE_MOD}\n",
            encoding="utf-8",
        )
        self._put_mod(
            BASE_MOD,
            {
                "scripts/keep.script": b"-- keep\n",
                "configs/items/x.ltx": b"[x]\n",
                "materials/material_pairs.ltx": b"[pair]\n",
                "text/rus/st.xml": b"<string/>\n",
                "textures/skip.dds": b"DDS",
                "meshes/skip.ogf": b"mesh",
            },
        )
        self._put_mod(
            SIMPLE_MOD,
            {"scripts/simple.script": b"function s() end\n"},
        )
        self._put_mod(
            DISABLED_MOD,
            {"scripts/old.script": b"-- old\n"},
        )
        (self.mods / SEPARATOR).mkdir()

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _put_mod(self, name: str, files: dict[str, bytes]) -> None:
        gamedata = self.mods / name / "gamedata"
        for relative, data in files.items():
            dest = gamedata.joinpath(*relative.split("/"))
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)

    def test_bytearray_profile_and_keep_dirs(self):
        code, out = run_fill(self.mo2, self.reference)
        self.assertEqual(code, 0, msg=out)
        addons = self.reference / "addons"
        base = addons / BASE_MOD
        self.assertEqual((base / "scripts" / "keep.script").read_bytes(), b"-- keep\n")
        self.assertEqual((base / "configs" / "items" / "x.ltx").read_bytes(), b"[x]\n")
        self.assertEqual(
            (base / "materials" / "material_pairs.ltx").read_bytes(), b"[pair]\n"
        )
        self.assertEqual((base / "text" / "rus" / "st.xml").read_bytes(), b"<string/>\n")
        self.assertFalse((base / "textures").exists())
        self.assertFalse((base / "meshes").exists())
        self.assertTrue((addons / SIMPLE_MOD / "scripts" / "simple.script").exists())
        self.assertFalse((addons / DISABLED_MOD).exists())
        self.assertFalse((addons / SEPARATOR).exists())
        self.assertIn("refindex.py build", out)
        self.assertIn(BASE_MOD, out)
        self.assertNotIn("keep.script", out)

    def test_dry_run_writes_nothing_and_does_not_list_files(self):
        code, out = run_fill(self.mo2, self.reference, "--dry-run")
        self.assertEqual(code, 0, msg=out)
        self.assertFalse((self.reference / "addons").exists())
        self.assertIn(SIMPLE_MOD, out)
        self.assertIn("попало бы", out)
        self.assertNotIn("keep.script", out)
        self.assertNotIn("simple.script", out)

    def test_profile_flag_overrides_ini(self):
        code, out = run_fill(self.mo2, self.reference, "--profile", HARD)
        self.assertEqual(code, 0, msg=out)
        addons = self.reference / "addons"
        self.assertTrue((addons / SIMPLE_MOD / "scripts" / "simple.script").exists())
        self.assertFalse((addons / BASE_MOD).exists())

    def test_idempotent_second_run(self):
        run_fill(self.mo2, self.reference)
        code, out = run_fill(self.mo2, self.reference)
        self.assertEqual(code, 0, msg=out)
        self.assertIn("без изменений:", out)
        self.assertIn("записано новых/изменённых: 0", out)

    def test_prune_without_yes_deletes_nothing(self):
        leftover = self.reference / "addons" / "Anthology Cutscenes v110 - leftover"
        leftover.mkdir(parents=True)
        marker = leftover / "scripts" / "old.script"
        marker.parent.mkdir()
        marker.write_bytes(b"-- leftover\n")
        code, out = run_fill(self.mo2, self.reference, "--prune")
        self.assertEqual(code, 0, msg=out)
        self.assertTrue(leftover.exists(), msg=out)
        self.assertTrue(marker.exists())
        self.assertIn("leftover", out)
        self.assertIn("--yes", out)
        self.assertFalse((self.reference / "addons" / SIMPLE_MOD).exists())

    def test_prune_yes_removes_extra(self):
        leftover = self.reference / "addons" / "Anthology Cutscenes v110 - leftover"
        leftover.mkdir(parents=True)
        (leftover / "marker.txt").write_text("gone", encoding="utf-8")
        code, out = run_fill(self.mo2, self.reference, "--prune", "--yes")
        self.assertEqual(code, 0, msg=out)
        self.assertFalse(leftover.exists(), msg=out)
        self.assertTrue(
            (self.reference / "addons" / SIMPLE_MOD / "scripts" / "simple.script").exists()
        )

    def test_skip_summary_missing_gamedata(self):
        empty = "mod_without_gamedata"
        (self.mods / empty).mkdir()
        modlist = self.profiles / STANDART / "modlist.txt"
        modlist.write_text(
            f"+{empty}\n+{SIMPLE_MOD}\n",
            encoding="utf-8",
        )
        code, out = run_fill(self.mo2, self.reference)
        self.assertEqual(code, 0, msg=out)
        self.assertIn("пропущено 1: нет gamedata (1)", out)
        self.assertTrue(
            (self.reference / "addons" / SIMPLE_MOD / "scripts" / "simple.script").exists()
        )


if __name__ == "__main__":
    unittest.main()
